[package]
name = "groq-discord"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
dotenvy = "0.15.7"
groq-api-rust = "0.2.51"
once_cell = "1.21.3"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
